INSERT INTO Hastaliklar (HastalikAdi) VALUES
(N'Anemi'),
(N'Alzheimer Hastalığı'),
(N'Diyabet'),
(N'Gastrointestinal Hastalıklar'),
(N'Hipoglisemi'),
(N'Hipertansiyon'),
(N'İnsülin Direnci'),
(N'İrritabl Bağırsak Sendromu'),
(N'Kanser'),
(N'Kalp Damar Hastalıkları'),
(N'Kemik Erimesi'),
(N'Obezite'),
(N'Parkinson Hastalığı'),
(N'Psoriatik Artrit'),
(N'Sedef Hastalığı'),
(N'Sindirim Sistemi Hastalıkları'),
(N'Tiroid Hastalıkları'),
(N'Çölyak Hastalığı'),
(N'Böbrek Hastalıkları'),
(N'Gut Hastalığı');