INSERT INTO Hastaliklar (HastalikAdi) VALUES
('Anemi (Kansızlık)'),
('Alzheimer Hastalığı'),
('Diyabet (Şeker Hastalığı'),
('Gastrointestinal Hastalıklar (Reflü, Ülser)'),
('Hipoglisemi (Düşük Kan Şekeri)'),
('Hipertansiyon (Yüksek Tansiyon)'),
('İnsülin Direnci'),
('İrritabl Bağırsak Sendromu (İBS)'),
('Kanser (Kemoterapi Sonrası Beslenme)'),
('Karaciğer Hastalıkları (Siroz, Hepatit vb.)'),
('Kalp-Damar Hastalıkları'),
('Obezite'),
('Osteoporoz (Kemik Erimesi)'),
('Parkinson Hastalığı'),
('Psoriatik Artrit'),
('Sedef Hastalığı'),
('Sindirim Sistemi Hastalıkları (Crohn, Colitis vb.)'),
('Tiroid Hastalıkları (Hipotiroidi, Hipertiroidi)'),
('Çölyak Hastalığı'),
('Böbrek Hastalıkları'),
('Gut Hastalığı');